pyuic5 CreateActor.ui -o CreateActor.py
pyuic5 CreatePerson.ui -o CreatePerson.py
pyuic5 CreateFilm.ui -o CreateFilm.py
pyuic5 CreateFilmInPlan.ui -o CreateFilmInProgress.py
pyuic5 CreateFilmInPlan.ui -o CreateFilmInPlan.py
pyuic5 profileActor.ui -o profileActor.py
pyuic5 profilePerson.ui -o profilePerson.py
pyuic5 profileFilm.ui -o profileFilm.py
pyuic5 profileFilmInPlan.ui -o profileFilmInProgress.py
pyuic5 profileFilmInPlan.ui -o profileFilmInPlan.py
pyuic5 TrueMain.ui -o TrueMain.py